import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'NL' | 'PL' | 'AR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'nav.services': 'Services',
    'nav.work': 'Work',
    'nav.packages': 'Packages',
    'nav.letstalk': "Let's Talk",
    'hero.headline.we': 'We Turn',
    'hero.headline.businesses': 'Businesses',
    'hero.headline.into': 'Into',
    'hero.headline.viral': 'Viral Brands.',
    'hero.subheadline': 'Built on 2+ Billion Monthly Views of Experience. Now Focused on Growing Your Business.',
    'hero.cta.book': 'Book Free Strategy Call',
    'hero.cta.view': 'View Case Studies',
    'authority.stats.views': 'Monthly Views',
    'authority.stats.clients': 'Active Clients',
    'authority.stats.roi': 'Average ROI',
    'authority.marquee.restaurants': 'Restaurants',
    'authority.marquee.cafes': 'Cafes',
    'authority.marquee.gyms': 'Gyms',
    'authority.marquee.clinics': 'Beauty Clinics',
    'authority.marquee.realestate': 'Real Estate',
    'problem.headline.great': 'Great',
    'problem.headline.business': 'Business.',
    'problem.headline.no': 'No',
    'problem.headline.attention': 'Attention.',
    'problem.step1.title': "You're Invisible Online",
    'problem.step1.desc': "You have the best food, service, or product in town, but nobody knows you exist. Word of mouth isn't enough anymore.",
    'problem.step2.title': 'Competitors Are Winning',
    'problem.step2.desc': 'Inferior businesses are stealing your customers simply because they have a better social media presence on TikTok and Instagram.',
    'problem.step3.title': 'Attention is Currency',
    'problem.step3.desc': "If you don't capture attention, you lose revenue. It's that simple. We help you monopolize local attention.",
    'problem.cta': 'Fix This Now',
    'solution.headline.our': 'Our Viral',
    'solution.headline.system': 'Growth System.',
    'solution.step1.title': 'We Visit & Film',
    'solution.step1.desc': 'We come to your business and professionally film high-performing content that showcases your unique value.',
    'solution.step2.title': 'Viral Concepts',
    'solution.step2.desc': 'We script, direct, and edit content specifically designed for organic reach and maximum engagement.',
    'solution.step3.title': 'Distribute & Optimize',
    'solution.step3.desc': 'We post across platforms and optimize the content to ensure it hits the right audience at the right time.',
    'solution.step4.title': 'More Customers',
    'solution.step4.desc': 'More visibility translates directly into more bookings, more foot traffic, and more revenue for your business.',
    'case.headline.proven': 'Proven',
    'case.headline.results': 'Results.',
    'case.cta': 'Start Yours',
    'case.category.restaurant': 'Restaurant',
    'case.category.tech': 'Tech / Gaming',
    'case.category.hospitality': 'Hospitality',
    'packages.headline.growth': 'Growth',
    'packages.headline.packages': 'Packages.',
    'packages.popular': 'Most Popular',
    'packages.period': '/mo',
    'packages.cta': 'Apply Now',
    'packages.feature.videos4': '4 videos per month',
    'packages.feature.videos6': '6 videos per month',
    'packages.feature.videos14': '14 videos per month',
    'packages.feature.filming': 'Professional Filming',
    'packages.feature.editing': 'High-end Editing',
    'packages.feature.concept': 'Concept Strategy',
    'packages.feature.distribution': 'Distribution Optimization',
    'packages.feature.fullviral': 'Full Viral Strategy',
    'packages.feature.priority': 'Priority Scheduling',
    'packages.feature.manager': 'Account Manager',
    'locations.headline.local': 'Local Focus.',
    'locations.headline.global': 'Global Ambition.',
    'locations.hq': 'HQ',
    'locations.expanding': 'Expanding Soon',
    'contact.headline.lets': "Let's",
    'contact.headline.talk': 'Talk.',
    'contact.desc': "Ready to dominate your local market? Fill out the form and we'll get back to you within 24 hours.",
    'contact.email': 'Email Us',
    'contact.follow': 'Follow Us',
    'contact.form.name': 'Name',
    'contact.form.business': 'Business Name',
    'contact.form.location': 'Location',
    'contact.form.revenue': 'Monthly Revenue (Optional)',
    'contact.form.revenue.select': 'Select Range',
    'contact.form.goal': 'What is your main goal?',
    'contact.form.cta': 'Request Strategy Call',
  },
  NL: {
    'nav.services': 'Diensten',
    'nav.work': 'Werk',
    'nav.packages': 'Pakketten',
    'nav.letstalk': 'Laten we praten',
    'hero.headline.we': 'Wij Veranderen',
    'hero.headline.businesses': 'Bedrijven',
    'hero.headline.into': 'In',
    'hero.headline.viral': 'Virale Merken.',
    'hero.subheadline': 'Gebouwd op 2+ Miljard Maandelijkse Weergaven aan Ervaring. Nu Gericht op de Groei van Uw Bedrijf.',
    'hero.cta.book': 'Boek Gratis Strategiegesprek',
    'hero.cta.view': 'Bekijk Casestudies',
    'authority.stats.views': 'Maandelijkse Weergaven',
    'authority.stats.clients': 'Actieve Klanten',
    'authority.stats.roi': 'Gemiddelde ROI',
    'authority.marquee.restaurants': 'Restaurants',
    'authority.marquee.cafes': 'Cafés',
    'authority.marquee.gyms': 'Sportscholen',
    'authority.marquee.clinics': 'Schoonheidsklinieken',
    'authority.marquee.realestate': 'Vastgoed',
    'problem.headline.great': 'Geweldig',
    'problem.headline.business': 'Bedrijf.',
    'problem.headline.no': 'Geen',
    'problem.headline.attention': 'Aandacht.',
    'problem.step1.title': 'Je bent onzichtbaar online',
    'problem.step1.desc': 'Je hebt het beste eten, de beste service of het beste product in de stad, maar niemand weet dat je bestaat. Mond-tot-mondreclame is niet meer genoeg.',
    'problem.step2.title': 'Concurrenten winnen',
    'problem.step2.desc': 'Inferieure bedrijven stelen je klanten simpelweg omdat ze een betere aanwezigheid op sociale media hebben op TikTok en Instagram.',
    'problem.step3.title': 'Aandacht is valuta',
    'problem.step3.desc': 'Als je geen aandacht trekt, verlies je inkomsten. Zo simpel is het. Wij helpen je lokale aandacht te monopoliseren.',
    'problem.cta': 'Los dit nu op',
    'solution.headline.our': 'Ons Virale',
    'solution.headline.system': 'Groeisysteem.',
    'solution.step1.title': 'Wij Bezoeken & Filmen',
    'solution.step1.desc': 'We komen naar uw bedrijf en filmen professioneel hoogwaardige content die uw unieke waarde laat zien.',
    'solution.step2.title': 'Virale Concepten',
    'solution.step2.desc': 'We schrijven, regisseren en bewerken content die specifiek is ontworpen voor organisch bereik en maximale betrokkenheid.',
    'solution.step3.title': 'Distribueren & Optimaliseren',
    'solution.step3.desc': 'We plaatsen op verschillende platforms en optimaliseren de content om ervoor te zorgen dat deze op het juiste moment de juiste doelgroep bereikt.',
    'solution.step4.title': 'Meer Klanten',
    'solution.step4.desc': 'Meer zichtbaarheid vertaalt zich direct in meer boekingen, meer bezoekers en meer omzet voor uw bedrijf.',
    'case.headline.proven': 'Bewezen',
    'case.headline.results': 'Resultaten.',
    'case.cta': 'Start Jouw Verhaal',
    'case.category.restaurant': 'Restaurant',
    'case.category.tech': 'Tech / Gaming',
    'case.category.hospitality': 'Horeca',
    'packages.headline.growth': 'Groei',
    'packages.headline.packages': 'Pakketten.',
    'packages.popular': 'Meest Populair',
    'packages.period': '/mnd',
    'packages.cta': 'Nu Aanvragen',
    'packages.feature.videos4': '4 video\'s per maand',
    'packages.feature.videos6': '6 video\'s per maand',
    'packages.feature.videos14': '14 video\'s per maand',
    'packages.feature.filming': 'Professioneel Filmen',
    'packages.feature.editing': 'High-end Bewerking',
    'packages.feature.concept': 'Conceptstrategie',
    'packages.feature.distribution': 'Distributie Optimalisatie',
    'packages.feature.fullviral': 'Volledige Virale Strategie',
    'packages.feature.priority': 'Prioriteit Planning',
    'packages.feature.manager': 'Accountmanager',
    'locations.headline.local': 'Lokale Focus.',
    'locations.headline.global': 'Globale Ambitie.',
    'locations.hq': 'Hoofdkantoor',
    'locations.expanding': 'Binnenkort Uitbreiden',
    'contact.headline.lets': 'Laten we',
    'contact.headline.talk': 'Praten.',
    'contact.desc': 'Klaar om je lokale markt te domineren? Vul het formulier in en we nemen binnen 24 uur contact met je op.',
    'contact.email': 'E-mail Ons',
    'contact.follow': 'Volg Ons',
    'contact.form.name': 'Naam',
    'contact.form.business': 'Bedrijfsnaam',
    'contact.form.location': 'Locatie',
    'contact.form.revenue': 'Maandelijkse Omzet (Optioneel)',
    'contact.form.revenue.select': 'Selecteer Bereik',
    'contact.form.goal': 'Wat is je belangrijkste doel?',
    'contact.form.cta': 'Vraag Strategiegesprek Aan',
  },
  PL: {
    'nav.services': 'Usługi',
    'nav.work': 'Praca',
    'nav.packages': 'Pakiety',
    'nav.letstalk': 'Porozmawiajmy',
    'hero.headline.we': 'Zmieniamy',
    'hero.headline.businesses': 'Firmy',
    'hero.headline.into': 'W',
    'hero.headline.viral': 'Viralowe Marki.',
    'hero.subheadline': 'Zbudowane na 2+ miliardach miesięcznych wyświetleń doświadczenia. Teraz skupieni na rozwoju Twojej firmy.',
    'hero.cta.book': 'Zarezerwuj Darmową Konsultację',
    'hero.cta.view': 'Zobacz Case Studies',
    'authority.stats.views': 'Miesięczne Wyświetlenia',
    'authority.stats.clients': 'Aktywni Klienci',
    'authority.stats.roi': 'Średni ROI',
    'authority.marquee.restaurants': 'Restauracje',
    'authority.marquee.cafes': 'Kawiarnie',
    'authority.marquee.gyms': 'Siłownie',
    'authority.marquee.clinics': 'Kliniki Urody',
    'authority.marquee.realestate': 'Nieruchomości',
    'problem.headline.great': 'Świetna',
    'problem.headline.business': 'Firma.',
    'problem.headline.no': 'Brak',
    'problem.headline.attention': 'Uwagi.',
    'problem.step1.title': 'Jesteś niewidoczny w sieci',
    'problem.step1.desc': 'Masz najlepsze jedzenie, usługi lub produkt w mieście, ale nikt nie wie, że istniejesz. Poczta pantoflowa to już za mało.',
    'problem.step2.title': 'Konkurencja wygrywa',
    'problem.step2.desc': 'Gorsze firmy kradną Twoich klientów tylko dlatego, że mają lepszą obecność w mediach społecznościowych na TikToku i Instagramie.',
    'problem.step3.title': 'Uwaga to waluta',
    'problem.step3.desc': 'Jeśli nie przyciągasz uwagi, tracisz przychody. To takie proste. Pomożemy Ci zmonopolizować lokalną uwagę.',
    'problem.cta': 'Napraw to teraz',
    'solution.headline.our': 'Nasz Wiralowy',
    'solution.headline.system': 'System Rozwoju.',
    'solution.step1.title': 'Odwiedzamy i Filmujemy',
    'solution.step1.desc': 'Przyjeżdżamy do Twojej firmy i profesjonalnie filmujemy wysokiej jakości treści, które ukazują Twoją unikalną wartość.',
    'solution.step2.title': 'Wiralowe Koncepcje',
    'solution.step2.desc': 'Piszemy scenariusze, reżyserujemy i montujemy treści zaprojektowane specjalnie pod kątem organicznego zasięgu i maksymalnego zaangażowania.',
    'solution.step3.title': 'Dystrybucja i Optymalizacja',
    'solution.step3.desc': 'Publikujemy na różnych platformach i optymalizujemy treści, aby upewnić się, że trafiają do odpowiedniej grupy docelowej w odpowiednim czasie.',
    'solution.step4.title': 'Więcej Klientów',
    'solution.step4.desc': 'Większa widoczność przekłada się bezpośrednio na więcej rezerwacji, większy ruch i większe przychody dla Twojej firmy.',
    'case.headline.proven': 'Udowodnione',
    'case.headline.results': 'Wyniki.',
    'case.cta': 'Zacznij Swój',
    'case.category.restaurant': 'Restauracja',
    'case.category.tech': 'Technologia / Gry',
    'case.category.hospitality': 'Hotelarstwo',
    'packages.headline.growth': 'Pakiety',
    'packages.headline.packages': 'Rozwojowe.',
    'packages.popular': 'Najpopularniejszy',
    'packages.period': '/msc',
    'packages.cta': 'Aplikuj Teraz',
    'packages.feature.videos4': '4 filmy miesięcznie',
    'packages.feature.videos6': '6 filmów miesięcznie',
    'packages.feature.videos14': '14 filmów miesięcznie',
    'packages.feature.filming': 'Profesjonalne Filmowanie',
    'packages.feature.editing': 'Wysokiej Klasy Montaż',
    'packages.feature.concept': 'Strategia Koncepcyjna',
    'packages.feature.distribution': 'Optymalizacja Dystrybucji',
    'packages.feature.fullviral': 'Pełna Strategia Wiralowa',
    'packages.feature.priority': 'Priorytetowe Planowanie',
    'packages.feature.manager': 'Opiekun Klienta',
    'locations.headline.local': 'Lokalne Skupienie.',
    'locations.headline.global': 'Globalna Ambicja.',
    'locations.hq': 'Centrala',
    'locations.expanding': 'Wkrótce Ekspansja',
    'contact.headline.lets': 'Porozmawiajmy',
    'contact.headline.talk': 'Teraz.',
    'contact.desc': 'Gotowy zdominować swój lokalny rynek? Wypełnij formularz, a my skontaktujemy się z Tobą w ciągu 24 godzin.',
    'contact.email': 'Napisz do nas',
    'contact.follow': 'Śledź nas',
    'contact.form.name': 'Imię i nazwisko',
    'contact.form.business': 'Nazwa firmy',
    'contact.form.location': 'Lokalizacja',
    'contact.form.revenue': 'Miesięczny Przychód (Opcjonalnie)',
    'contact.form.revenue.select': 'Wybierz Przedział',
    'contact.form.goal': 'Jaki jest Twój główny cel?',
    'contact.form.cta': 'Poproś o Konsultację',
  },
  AR: {
    'nav.services': 'خدماتنا',
    'nav.work': 'أعمالنا',
    'nav.packages': 'الباقات',
    'nav.letstalk': 'لنتحدث',
    'hero.headline.we': 'نحول',
    'hero.headline.businesses': 'الشركات',
    'hero.headline.into': 'إلى',
    'hero.headline.viral': 'علامات تجارية سريعة الانتشار.',
    'hero.subheadline': 'مبني على خبرة أكثر من 2 مليار مشاهدة شهرية. نركز الآن على تنمية عملك.',
    'hero.cta.book': 'احجز مكالمة استراتيجية مجانية',
    'hero.cta.view': 'عرض دراسات الحالة',
    'authority.stats.views': 'مشاهدات شهرية',
    'authority.stats.clients': 'عملاء نشطون',
    'authority.stats.roi': 'متوسط العائد على الاستثمار',
    'authority.marquee.restaurants': 'مطاعم',
    'authority.marquee.cafes': 'مقاهي',
    'authority.marquee.gyms': 'صالات رياضية',
    'authority.marquee.clinics': 'عيادات تجميل',
    'authority.marquee.realestate': 'عقارات',
    'problem.headline.great': 'عمل',
    'problem.headline.business': 'رائع.',
    'problem.headline.no': 'لا يوجد',
    'problem.headline.attention': 'انتباه.',
    'problem.step1.title': 'أنت غير مرئي على الإنترنت',
    'problem.step1.desc': 'لديك أفضل طعام أو خدمة أو منتج في المدينة، لكن لا أحد يعرف بوجودك. الكلام الشفهي لم يعد كافياً.',
    'problem.step2.title': 'المنافسون يفوزون',
    'problem.step2.desc': 'الشركات الأقل جودة تسرق عملائك ببساطة لأن لديهم حضور أفضل على وسائل التواصل الاجتماعي على TikTok و Instagram.',
    'problem.step3.title': 'الاهتمام هو العملة',
    'problem.step3.desc': 'إذا لم تجذب الانتباه، تفقد الإيرادات. الأمر بهذه البساطة. نحن نساعدك على احتكار الاهتمام المحلي.',
    'problem.cta': 'أصلح هذا الآن',
    'solution.headline.our': 'نظام',
    'solution.headline.system': 'النمو السريع.',
    'solution.step1.title': 'نزور ونصور',
    'solution.step1.desc': 'نأتي إلى عملك ونقوم بتصوير محتوى عالي الأداء باحترافية يعرض قيمتك الفريدة.',
    'solution.step2.title': 'مفاهيم سريعة الانتشار',
    'solution.step2.desc': 'نقوم بكتابة وتوجيه وتحرير المحتوى المصمم خصيصًا للوصول العضوي وأقصى قدر من التفاعل.',
    'solution.step3.title': 'توزيع وتحسين',
    'solution.step3.desc': 'نقوم بالنشر عبر المنصات وتحسين المحتوى لضمان وصوله إلى الجمهور المناسب في الوقت المناسب.',
    'solution.step4.title': 'المزيد من العملاء',
    'solution.step4.desc': 'المزيد من الرؤية يترجم مباشرة إلى المزيد من الحجوزات والمزيد من حركة المرور والمزيد من الإيرادات لعملك.',
    'case.headline.proven': 'نتائج',
    'case.headline.results': 'مضمونة.',
    'case.cta': 'ابدأ قصتك',
    'case.category.restaurant': 'مطعم',
    'case.category.tech': 'تكنولوجيا / ألعاب',
    'case.category.hospitality': 'ضيافة',
    'packages.headline.growth': 'باقات',
    'packages.headline.packages': 'النمو.',
    'packages.popular': 'الأكثر شعبية',
    'packages.period': '/شهر',
    'packages.cta': 'قدم الآن',
    'packages.feature.videos4': '4 مقاطع فيديو شهريًا',
    'packages.feature.videos6': '6 مقاطع فيديو شهريًا',
    'packages.feature.videos14': '14 مقطع فيديو شهريًا',
    'packages.feature.filming': 'تصوير احترافي',
    'packages.feature.editing': 'تحرير عالي الجودة',
    'packages.feature.concept': 'استراتيجية المفهوم',
    'packages.feature.distribution': 'تحسين التوزيع',
    'packages.feature.fullviral': 'استراتيجية انتشار كاملة',
    'packages.feature.priority': 'جدولة ذات أولوية',
    'packages.feature.manager': 'مدير حساب',
    'locations.headline.local': 'تركيز محلي.',
    'locations.headline.global': 'طموح عالمي.',
    'locations.hq': 'المقر الرئيسي',
    'locations.expanding': 'نتوسع قريباً',
    'contact.headline.lets': 'دعنا',
    'contact.headline.talk': 'نتحدث.',
    'contact.desc': 'هل أنت مستعد للسيطرة على سوقك المحلي؟ املأ النموذج وسنرد عليك في غضون 24 ساعة.',
    'contact.email': 'راسلنا',
    'contact.follow': 'تابعنا',
    'contact.form.name': 'الاسم',
    'contact.form.business': 'اسم الشركة',
    'contact.form.location': 'الموقع',
    'contact.form.revenue': 'الإيرادات الشهرية (اختياري)',
    'contact.form.revenue.select': 'اختر النطاق',
    'contact.form.goal': 'ما هو هدفك الرئيسي؟',
    'contact.form.cta': 'اطلب مكالمة استراتيجية',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'AR' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
