import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'NL' | 'PL' | 'AR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'nav.services': 'Services',
    'nav.work': 'Work',
    'nav.packages': 'Packages',
    'nav.letstalk': "Let's Talk",
    'hero.headline.we': 'We Turn',
    'hero.headline.businesses': 'Businesses',
    'hero.headline.into': 'Into',
    'hero.headline.viral': 'Viral Brands.',
    'hero.subheadline': 'Built on 2+ Billion Monthly Views of Experience. Now Focused on Growing Your Business.',
    'hero.cta.book': 'Book Free Strategy Call',
    'hero.cta.view': 'View Case Studies',
    'authority.stats.views': 'Monthly Views',
    'authority.stats.unique': 'Unique Viewers',
    'authority.stats.followers': 'Followers',
    'authority.stats.reach': 'Audience Reach',
    'authority.stats.clients': 'Active Clients',
    'authority.stats.roi': 'Average ROI',
    'authority.marquee.restaurants': 'Restaurants',
    'authority.marquee.cafes': 'Cafes',
    'authority.marquee.gyms': 'Gyms',
    'authority.marquee.clinics': 'Beauty Clinics',
    'authority.marquee.realestate': 'Real Estate',
    'problem.headline.great': 'Great',
    'problem.headline.business': 'Business.',
    'problem.headline.no': 'No',
    'problem.headline.attention': 'Attention.',
    'problem.step1.title': "You're Invisible Online",
    'problem.step1.desc': "You have the best food, service, or product in town, but nobody knows you exist. Word of mouth isn't enough anymore.",
    'problem.step2.title': 'Competitors Are Winning',
    'problem.step2.desc': 'Inferior businesses are stealing your customers simply because they have a better social media presence on TikTok and Instagram.',
    'problem.step3.title': 'Attention is Currency',
    'problem.step3.desc': "If you don't capture attention, you lose revenue. It's that simple. We help you monopolize local attention.",
    'problem.cta': 'Fix This Now',
    'solution.headline.our': 'Our Viral',
    'solution.headline.system': 'Growth System.',
    'solution.step1.title': 'We Visit & Film',
    'solution.step1.desc': 'We come to your business and professionally film high-performing content that showcases your unique value.',
    'solution.step2.title': 'Viral Concepts',
    'solution.step2.desc': 'We script, direct, and edit content specifically designed for organic reach and maximum engagement.',
    'solution.step3.title': 'Distribute & Optimize',
    'solution.step3.desc': 'We post across platforms and optimize the content to ensure it hits the right audience at the right time.',
    'solution.step4.title': 'More Customers',
    'solution.step4.desc': 'More visibility translates directly into more bookings, more foot traffic, and more revenue for your business.',
    'deliverables.headline.viral': 'Viral',
    'deliverables.headline.deliverables': 'Deliverables.',
    'deliverables.subheadline': 'We produce high-converting content in multiple languages, tailored for global and local audiences.',
    'deliverables.comments': 'comments',
    'deliverables.lang.en': 'English 🇺🇸',
    'deliverables.lang.nl': 'Dutch 🇳🇱',
    'deliverables.lang.ar': 'Arabic 🇦🇪',
    'deliverables.lang.pl': 'Polish 🇵🇱',
    'omer.headline.meet': 'Meet',
    'omer.headline.name': 'Omer Sastim.',
    'omer.role': 'Chief Viral Officer',
    'omer.desc': 'Known globally as Masteroogway, Omer is the mastermind behind some of the internet\'s most viral moments. With billions of views under his belt, he knows exactly what makes content explode.',
    'omer.feature1.title': 'The Viral Formula',
    'omer.feature1.desc': 'Omer applies his proven psychological triggers and retention hacks to your business, ensuring every video has the potential to reach millions.',
    'omer.feature2.title': 'Massive Audience',
    'omer.feature2.desc': 'He doesn\'t just create content; he knows how to distribute it. Leveraging his network and expertise to put your brand in front of the right eyeballs.',
    'omer.cta': 'Work With Omer',
    'case.headline.proven': 'Proven',
    'case.headline.results': 'Results.',
    'case.cta': 'Start Yours',
    'case.category.restaurant': 'Restaurant',
    'case.category.tech': 'Tech / Gaming',
    'case.category.hospitality': 'Hospitality',
    'case.results.views': 'Views',
    'case.results.users': 'Users',
    'case.results.for1video': 'for 1 video',
    'packages.headline.growth': 'Growth',
    'packages.headline.packages': 'Packages.',
    'packages.popular': 'Most Popular',
    'packages.period': '/mo',
    'packages.cta': 'Apply Now',
    'packages.starter.name': 'Starter',
    'packages.growth.name': 'Growth',
    'packages.authority.name': 'Authority',
    'packages.feature.videos4': '4 videos per month',
    'packages.feature.videos6': '6 videos per month',
    'packages.feature.videos14': '14 videos per month',
    'packages.feature.filming': 'Professional Filming',
    'packages.feature.editing': 'High-end Editing',
    'packages.feature.concept': 'Concept Strategy',
    'packages.feature.distribution': 'Distribution Optimization',
    'packages.feature.fullviral': 'Full Viral Strategy',
    'packages.feature.priority': 'Priority Scheduling',
    'packages.feature.manager': 'Account Manager',
    'packages.budget.headline': 'Have a different budget? No problem — we’ll tailor the package to fit your needs.',
    'packages.budget.cta': "Let's talk.",
    'locations.headline.local': 'Local Focus.',
    'locations.headline.global': 'Global Ambition.',
    'locations.hq': 'HQ',
    'locations.expanding': 'Expanding Soon',
    'contact.headline.lets': "Let's",
    'contact.headline.talk': 'Talk.',
    'contact.desc': "Ready to dominate your local market? Fill out the form and we'll get back to you within 24 hours.",
    'contact.email': 'Email Us',
    'contact.follow': 'Follow Us',
    'contact.form.name': 'Name',
    'contact.form.business': 'Business Name',
    'contact.form.location': 'Location',
    'contact.form.revenue': 'Monthly Revenue (Optional)',
    'contact.form.revenue.select': 'Select Range',
    'contact.form.goal': 'What is your main goal?',
    'contact.form.cta': 'Request Strategy Call',
    'authority.headline.numbers': 'The Numbers',
    'authority.headline.speak': 'Speak For',
    'authority.headline.themselves': 'Themselves.',
    'authority.desc': "We don't just talk about going viral. We live it every single day. Our strategies are tested on millions before they reach your brand.",
    'authority.cta': 'Verify on Instagram',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'customBudget.title': 'Flexible Pricing for Every Budget',
    'customBudget.subtitle': 'Have a lower or higher budget or inbetween the prices given? No problem, we can always adjust the video amount to your needs.',
    'customBudget.label': 'Your Available Budget',
    'customBudget.cta': 'Get This Offer',
  },
  NL: {
    'nav.services': 'Diensten',
    'nav.work': 'Werk',
    'nav.packages': 'Pakketten',
    'nav.letstalk': 'Laten we praten',
    'hero.headline.we': 'Wij Veranderen',
    'hero.headline.businesses': 'Bedrijven',
    'hero.headline.into': 'In',
    'hero.headline.viral': 'Virale Merken.',
    'hero.subheadline': 'Gebouwd op 2+ Miljard Maandelijkse Weergaven aan Ervaring. Nu Gericht op de Groei van Uw Bedrijf.',
    'hero.cta.book': 'Boek Gratis Strategiegesprek',
    'hero.cta.view': 'Bekijk Casestudies',
    'authority.stats.views': 'Maandelijkse Weergaven',
    'authority.stats.unique': 'Unieke Kijkers',
    'authority.stats.followers': 'Volgers',
    'authority.stats.reach': 'Publieksbereik',
    'authority.stats.clients': 'Actieve Klanten',
    'authority.stats.roi': 'Gemiddelde ROI',
    'authority.marquee.restaurants': 'Restaurants',
    'authority.marquee.cafes': 'Cafés',
    'authority.marquee.gyms': 'Sportscholen',
    'authority.marquee.clinics': 'Schoonheidsklinieken',
    'authority.marquee.realestate': 'Vastgoed',
    'problem.headline.great': 'Geweldig',
    'problem.headline.business': 'Bedrijf.',
    'problem.headline.no': 'Geen',
    'problem.headline.attention': 'Aandacht.',
    'problem.step1.title': 'Je bent onzichtbaar online',
    'problem.step1.desc': 'Je hebt het beste eten, de beste service of het beste product in de stad, maar niemand weet dat je bestaat. Mond-tot-mondreclame is niet meer genoeg.',
    'problem.step2.title': 'Concurrenten winnen',
    'problem.step2.desc': 'Inferieure bedrijven stelen je klanten simpelweg omdat ze een betere aanwezigheid op sociale media hebben op TikTok en Instagram.',
    'problem.step3.title': 'Aandacht is valuta',
    'problem.step3.desc': 'Als je geen aandacht trekt, verlies je inkomsten. Zo simpel is het. Wij helpen je lokale aandacht te monopoliseren.',
    'problem.cta': 'Los dit nu op',
    'solution.headline.our': 'Ons Virale',
    'solution.headline.system': 'Groeisysteem.',
    'solution.step1.title': 'Wij Bezoeken & Filmen',
    'solution.step1.desc': 'We komen naar uw bedrijf en filmen professioneel hoogwaardige content die uw unieke waarde laat zien.',
    'solution.step2.title': 'Virale Concepten',
    'solution.step2.desc': 'We schrijven, regisseren en bewerken content die specifiek is ontworpen voor organisch bereik en maximale betrokkenheid.',
    'solution.step3.title': 'Distribueren & Optimaliseren',
    'solution.step3.desc': 'We plaatsen op verschillende platforms en optimaliseren de content om ervoor te zorgen dat deze op het juiste moment de juiste doelgroep bereikt.',
    'solution.step4.title': 'Meer Klanten',
    'solution.step4.desc': 'Meer zichtbaarheid vertaalt zich direct in meer boekingen, meer bezoekers en meer omzet voor uw bedrijf.',
    'deliverables.headline.viral': 'Virale',
    'deliverables.headline.deliverables': 'Resultaten.',
    'deliverables.subheadline': 'Wij produceren content met een hoge conversie in meerdere talen, op maat gemaakt voor een wereldwijd en lokaal publiek.',
    'deliverables.comments': 'reacties',
    'deliverables.lang.en': 'Engels 🇺🇸',
    'deliverables.lang.nl': 'Nederlands 🇳🇱',
    'deliverables.lang.ar': 'Arabisch 🇦🇪',
    'deliverables.lang.pl': 'Pools 🇵🇱',
    'omer.headline.meet': 'Ontmoet',
    'omer.headline.name': 'Omer Sastim.',
    'omer.role': 'Chief Viral Officer',
    'omer.desc': 'Wereldwijd bekend als Masteroogway, Omer is het brein achter enkele van de meest virale momenten op internet. Met miljarden weergaven op zijn naam, weet hij precies wat content laat exploderen.',
    'omer.feature1.title': 'De Virale Formule',
    'omer.feature1.desc': 'Omer past zijn bewezen psychologische triggers en retentie-hacks toe op uw bedrijf, zodat elke video het potentieel heeft om miljoenen te bereiken.',
    'omer.feature2.title': 'Enorm Publiek',
    'omer.feature2.desc': 'Hij maakt niet alleen content; hij weet hoe hij het moet distribueren. Hij gebruikt zijn netwerk en expertise om uw merk onder de aandacht van de juiste mensen te brengen.',
    'omer.cta': 'Werk met Omer',
    'case.headline.proven': 'Bewezen',
    'case.headline.results': 'Resultaten.',
    'case.cta': 'Start Jouw Verhaal',
    'case.category.restaurant': 'Restaurant',
    'case.category.tech': 'Tech / Gaming',
    'case.category.hospitality': 'Horeca',
    'case.results.views': 'Weergaven',
    'case.results.users': 'Gebruikers',
    'case.results.for1video': 'voor 1 video',
    'packages.headline.growth': 'Groei',
    'packages.headline.packages': 'Pakketten.',
    'packages.popular': 'Meest Populair',
    'packages.period': '/mnd',
    'packages.cta': 'Nu Aanvragen',
    'packages.starter.name': 'Starter',
    'packages.growth.name': 'Groei',
    'packages.authority.name': 'Autoriteit',
    'packages.feature.videos4': '4 video\'s per maand',
    'packages.feature.videos6': '6 video\'s per maand',
    'packages.feature.videos14': '14 video\'s per maand',
    'packages.feature.filming': 'Professioneel Filmen',
    'packages.feature.editing': 'High-end Bewerking',
    'packages.feature.concept': 'Conceptstrategie',
    'packages.feature.distribution': 'Distributie Optimalisatie',
    'packages.feature.fullviral': 'Volledige Virale Strategie',
    'packages.feature.priority': 'Prioriteit Planning',
    'packages.feature.manager': 'Accountmanager',
    'packages.budget.headline': 'Heb je een ander budget? Geen probleem — we passen het pakket aan jouw behoeften aan.',
    'packages.budget.cta': 'Laten we praten.',
    'locations.headline.local': 'Lokale Focus.',
    'locations.headline.global': 'Globale Ambitie.',
    'locations.hq': 'Hoofdkantoor',
    'locations.expanding': 'Binnenkort Uitbreiden',
    'contact.headline.lets': 'Laten we',
    'contact.headline.talk': 'Praten.',
    'contact.desc': 'Klaar om je lokale markt te domineren? Vul het formulier in en we nemen binnen 24 uur contact met je op.',
    'contact.email': 'E-mail Ons',
    'contact.follow': 'Volg Ons',
    'contact.form.name': 'Naam',
    'contact.form.business': 'Bedrijfsnaam',
    'contact.form.location': 'Locatie',
    'contact.form.revenue': 'Maandelijkse Omzet (Optioneel)',
    'contact.form.revenue.select': 'Selecteer Bereik',
    'contact.form.goal': 'Wat is je belangrijkste doel?',
    'contact.form.cta': 'Vraag Strategiegesprek Aan',
    'authority.headline.numbers': 'De Cijfers',
    'authority.headline.speak': 'Spreken Voor',
    'authority.headline.themselves': 'Zichzelf.',
    'authority.desc': "We praten niet alleen over viraal gaan. We beleven het elke dag. Onze strategieën worden getest op miljoenen voordat ze uw merk bereiken.",
    'authority.cta': 'Verifieer op Instagram',
    'footer.rights': 'Alle rechten voorbehouden.',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Servicevoorwaarden',
    'customBudget.title': 'Flexibele Prijzen voor Elk Budget',
    'customBudget.subtitle': 'Heb je een lager of hoger budget of iets daartussenin? Geen probleem, we kunnen het aantal video\'s altijd aanpassen aan jouw behoeften.',
    'customBudget.label': 'Jouw Beschikbare Budget',
    'customBudget.cta': 'Ontvang Dit Aanbod',
  },
  PL: {
    'nav.services': 'Usługi',
    'nav.work': 'Praca',
    'nav.packages': 'Pakiety',
    'nav.letstalk': 'Porozmawiajmy',
    'hero.headline.we': 'Zmieniamy',
    'hero.headline.businesses': 'Firmy',
    'hero.headline.into': 'W',
    'hero.headline.viral': 'Viralowe Marki.',
    'hero.subheadline': 'Zbudowane na 2+ miliardach miesięcznych wyświetleń doświadczenia. Teraz skupieni na rozwoju Twojej firmy.',
    'hero.cta.book': 'Zarezerwuj Darmową Konsultację',
    'hero.cta.view': 'Zobacz Case Studies',
    'authority.stats.views': 'Miesięczne Wyświetlenia',
    'authority.stats.unique': 'Unikalni Widzowie',
    'authority.stats.followers': 'Obserwujących',
    'authority.stats.reach': 'Zasięg',
    'authority.stats.clients': 'Aktywni Klienci',
    'authority.stats.roi': 'Średni ROI',
    'authority.marquee.restaurants': 'Restauracje',
    'authority.marquee.cafes': 'Kawiarnie',
    'authority.marquee.gyms': 'Siłownie',
    'authority.marquee.clinics': 'Kliniki Urody',
    'authority.marquee.realestate': 'Nieruchomości',
    'problem.headline.great': 'Świetna',
    'problem.headline.business': 'Firma.',
    'problem.headline.no': 'Brak',
    'problem.headline.attention': 'Uwagi.',
    'problem.step1.title': 'Jesteś niewidoczny w sieci',
    'problem.step1.desc': 'Masz najlepsze jedzenie, usługi lub produkt w mieście, ale nikt nie wie, że istniejesz. Poczta pantoflowa to już za mało.',
    'problem.step2.title': 'Konkurencja wygrywa',
    'problem.step2.desc': 'Gorsze firmy kradną Twoich klientów tylko dlatego, że mają lepszą obecność w mediach społecznościowych na TikToku i Instagramie.',
    'problem.step3.title': 'Uwaga to waluta',
    'problem.step3.desc': 'Jeśli nie przyciągasz uwagi, tracisz przychody. To takie proste. Pomożemy Ci zmonopolizować lokalną uwagę.',
    'problem.cta': 'Napraw to teraz',
    'solution.headline.our': 'Nasz Wiralowy',
    'solution.headline.system': 'System Rozwoju.',
    'solution.step1.title': 'Odwiedzamy i Filmujemy',
    'solution.step1.desc': 'Przyjeżdżamy do Twojej firmy i profesjonalnie filmujemy wysokiej jakości treści, które ukazują Twoją unikalną wartość.',
    'solution.step2.title': 'Wiralowe Koncepcje',
    'solution.step2.desc': 'Piszemy scenariusze, reżyserujemy i montujemy treści zaprojektowane specjalnie pod kątem organicznego zasięgu i maksymalnego zaangażowania.',
    'solution.step3.title': 'Dystrybucja i Optymalizacja',
    'solution.step3.desc': 'Publikujemy na różnych platformach i optymalizujemy treści, aby upewnić się, że trafiają do odpowiedniej grupy docelowej w odpowiednim czasie.',
    'solution.step4.title': 'Więcej Klientów',
    'solution.step4.desc': 'Większa widoczność przekłada się bezpośrednio na więcej rezerwacji, większy ruch i większe przychody dla Twojej firmy.',
    'deliverables.headline.viral': 'Viralowe',
    'deliverables.headline.deliverables': 'Realizacje.',
    'deliverables.subheadline': 'Tworzymy treści o wysokiej konwersji w wielu językach, dostosowane do odbiorców globalnych i lokalnych.',
    'deliverables.comments': 'komentarzy',
    'deliverables.lang.en': 'Angielski 🇺🇸',
    'deliverables.lang.nl': 'Holenderski 🇳🇱',
    'deliverables.lang.ar': 'Arabski 🇦🇪',
    'deliverables.lang.pl': 'Polski 🇵🇱',
    'omer.headline.meet': 'Poznaj',
    'omer.headline.name': 'Omera Sastima.',
    'omer.role': 'Chief Viral Officer',
    'omer.desc': 'Znany na całym świecie jako Masteroogway, Omer jest mózgiem stojącym za najbardziej viralowymi momentami w internecie. Mając na koncie miliardy wyświetleń, dokładnie wie, co sprawia, że treści eksplodują.',
    'omer.feature1.title': 'Viralowa Formuła',
    'omer.feature1.desc': 'Omer stosuje swoje sprawdzone wyzwalacze psychologiczne i triki zwiększające retencję w Twojej firmie, zapewniając, że każdy film ma potencjał dotarcia do milionów.',
    'omer.feature2.title': 'Ogromna Publiczność',
    'omer.feature2.desc': 'On nie tylko tworzy treści; wie, jak je dystrybuować. Wykorzystuje swoją sieć kontaktów i wiedzę, aby umieścić Twoją markę przed właściwymi ludźmi.',
    'omer.cta': 'Współpracuj z Omerem',
    'case.headline.proven': 'Udowodnione',
    'case.headline.results': 'Wyniki.',
    'case.cta': 'Zacznij Swój',
    'case.category.restaurant': 'Restauracja',
    'case.category.tech': 'Technologia / Gry',
    'case.category.hospitality': 'Hotelarstwo',
    'case.results.views': 'Wyświetleń',
    'case.results.users': 'Użytkowników',
    'case.results.for1video': 'za 1 film',
    'packages.headline.growth': 'Pakiety',
    'packages.headline.packages': 'Rozwojowe.',
    'packages.popular': 'Najpopularniejszy',
    'packages.period': '/msc',
    'packages.cta': 'Aplikuj Teraz',
    'packages.starter.name': 'Starter',
    'packages.growth.name': 'Growth',
    'packages.authority.name': 'Authority',
    'packages.feature.videos4': '4 filmy miesięcznie',
    'packages.feature.videos6': '6 filmów miesięcznie',
    'packages.feature.videos14': '14 filmów miesięcznie',
    'packages.feature.filming': 'Profesjonalne Filmowanie',
    'packages.feature.editing': 'Wysokiej Klasy Montaż',
    'packages.feature.concept': 'Strategia Koncepcyjna',
    'packages.feature.distribution': 'Optymalizacja Dystrybucji',
    'packages.feature.fullviral': 'Pełna Strategia Wiralowa',
    'packages.feature.priority': 'Priorytetowe Planowanie',
    'packages.feature.manager': 'Opiekun Klienta',
    'packages.budget.headline': 'Masz inny budżet? Nie ma problemu — dostosujemy pakiet do Twoich potrzeb.',
    'packages.budget.cta': 'Porozmawiajmy.',
    'locations.headline.local': 'Lokalne Skupienie.',
    'locations.headline.global': 'Globalna Ambicja.',
    'locations.hq': 'Centrala',
    'locations.expanding': 'Wkrótce Ekspansja',
    'contact.headline.lets': 'Porozmawiajmy',
    'contact.headline.talk': 'Teraz.',
    'contact.desc': 'Gotowy zdominować swój lokalny rynek? Wypełnij formularz, a my skontaktujemy się z Tobą w ciągu 24 godzin.',
    'contact.email': 'Napisz do nas',
    'contact.follow': 'Śledź nas',
    'contact.form.name': 'Imię i nazwisko',
    'contact.form.business': 'Nazwa firmy',
    'contact.form.location': 'Lokalizacja',
    'contact.form.revenue': 'Miesięczny Przychód (Opcjonalnie)',
    'contact.form.revenue.select': 'Wybierz Przedział',
    'contact.form.goal': 'Jaki jest Twój główny cel?',
    'contact.form.cta': 'Poproś o Konsultację',
    'authority.headline.numbers': 'Liczby',
    'authority.headline.speak': 'Mówią Same',
    'authority.headline.themselves': 'Za Siebie.',
    'authority.desc': "Nie tylko mówimy o viralach. Żyjemy nimi każdego dnia. Nasze strategie są testowane na milionach, zanim trafią do Twojej marki.",
    'authority.cta': 'Zweryfikuj na Instagramie',
    'footer.rights': 'Wszelkie prawa zastrzeżone.',
    'footer.privacy': 'Polityka prywatności',
    'footer.terms': 'Warunki korzystania',
    'customBudget.title': 'Elastyczne Ceny na Każdy Budżet',
    'customBudget.subtitle': 'Masz niższy lub wyższy budżet, a może coś pomiędzy? Żaden problem, zawsze możemy dostosować liczbę filmów do Twoich potrzeb.',
    'customBudget.label': 'Twój Dostępny Budżet',
    'customBudget.cta': 'Skorzystaj z Tej Oferty',
  },
  AR: {
    'nav.services': 'خدماتنا',
    'nav.work': 'أعمالنا',
    'nav.packages': 'الباقات',
    'nav.letstalk': 'لنتحدث',
    'hero.headline.we': 'نحول',
    'hero.headline.businesses': 'الشركات',
    'hero.headline.into': 'إلى',
    'hero.headline.viral': 'علامات تجارية سريعة الانتشار.',
    'hero.subheadline': 'مبني على خبرة أكثر من 2 مليار مشاهدة شهرية. نركز الآن على تنمية عملك.',
    'hero.cta.book': 'احجز مكالمة استراتيجية مجانية',
    'hero.cta.view': 'عرض دراسات الحالة',
    'authority.stats.views': 'مشاهدات شهرية',
    'authority.stats.unique': 'مشاهدون فريدون',
    'authority.stats.followers': 'متابعين',
    'authority.stats.reach': 'وصول الجمهور',
    'authority.stats.clients': 'عملاء نشطون',
    'authority.stats.roi': 'متوسط العائد على الاستثمار',
    'authority.marquee.restaurants': 'مطاعم',
    'authority.marquee.cafes': 'مقاهي',
    'authority.marquee.gyms': 'صالات رياضية',
    'authority.marquee.clinics': 'عيادات تجميل',
    'authority.marquee.realestate': 'عقارات',
    'problem.headline.great': 'عمل',
    'problem.headline.business': 'رائع.',
    'problem.headline.no': 'لا يوجد',
    'problem.headline.attention': 'انتباه.',
    'problem.step1.title': 'أنت غير مرئي على الإنترنت',
    'problem.step1.desc': 'لديك أفضل طعام أو خدمة أو منتج في المدينة، لكن لا أحد يعرف بوجودك. الكلام الشفهي لم يعد كافياً.',
    'problem.step2.title': 'المنافسون يفوزون',
    'problem.step2.desc': 'الشركات الأقل جودة تسرق عملائك ببساطة لأن لديهم حضور أفضل على وسائل التواصل الاجتماعي على TikTok و Instagram.',
    'problem.step3.title': 'الاهتمام هو العملة',
    'problem.step3.desc': 'إذا لم تجذب الانتباه، تفقد الإيرادات. الأمر بهذه البساطة. نحن نساعدك على احتكار الاهتمام المحلي.',
    'problem.cta': 'أصلح هذا الآن',
    'solution.headline.our': 'نظام',
    'solution.headline.system': 'النمو السريع.',
    'solution.step1.title': 'نحن نزور ونصور',
    'solution.step1.desc': 'نأتي إلى عملك ونقوم بتصوير محتوى عالي الأداء باحترافية يعرض قيمتك الفريدة.',
    'solution.step2.title': 'مفاهيم سريعة الانتشار',
    'solution.step2.desc': 'نقوم بكتابة وتوجيه وتحرير المحتوى المصمم خصيصًا للوصول العضوي وأقصى قدر من التفاعل.',
    'solution.step3.title': 'توزيع وتحسين',
    'solution.step3.desc': 'نقوم بالنشر عبر المنصات وتحسين المحتوى لضمان وصوله إلى الجمهور المناسب في الوقت المناسب.',
    'solution.step4.title': 'المزيد من العملاء',
    'solution.step4.desc': 'المزيد من الرؤية يترجم مباشرة إلى المزيد من الحجوزات والمزيد من حركة المرور والمزيد من الإيرادات لعملك.',
    'deliverables.headline.viral': 'نتائج',
    'deliverables.headline.deliverables': 'سريعة الانتشار.',
    'deliverables.subheadline': 'نحن ننتج محتوى عالي التحويل بلغات متعددة، مصمم خصيصًا للجمهور العالمي والمحلي.',
    'deliverables.comments': 'تعليق',
    'deliverables.lang.en': 'الإنجليزية 🇺🇸',
    'deliverables.lang.nl': 'الهولندية 🇳🇱',
    'deliverables.lang.ar': 'العربية 🇦🇪',
    'deliverables.lang.pl': 'البولندية 🇵🇱',
    'omer.headline.meet': 'تعرف على',
    'omer.headline.name': 'عمر صاستيم.',
    'omer.role': 'رئيس قسم الانتشار السريع',
    'omer.desc': 'المعروف عالميًا باسم Masteroogway، عمر هو العقل المدبر وراء بعض أكثر اللحظات انتشارًا على الإنترنت. مع مليارات المشاهدات، يعرف بالضبط ما الذي يجعل المحتوى ينفجر.',
    'omer.feature1.title': 'صيغة الانتشار',
    'omer.feature1.desc': 'يطبق عمر محفزاته النفسية المثبتة وحيل الاحتفاظ بالجمهور على عملك، مما يضمن أن كل فيديو لديه القدرة على الوصول إلى الملايين.',
    'omer.feature2.title': 'جمهور هائل',
    'omer.feature2.desc': 'هو لا يكتفي بإنشاء المحتوى فحسب؛ بل يعرف كيف يوزعه. يستفيد من شبكته وخبرته لوضع علامتك التجارية أمام الأعين المناسبة.',
    'omer.cta': 'اعمل مع عمر',
    'case.headline.proven': 'نتائج',
    'case.headline.results': 'مثبتة.',
    'case.cta': 'ابدأ قصتك',
    'case.category.restaurant': 'مطعم',
    'case.category.tech': 'تكنولوجيا / ألعاب',
    'case.category.hospitality': 'ضيافة',
    'case.results.views': 'مشاهدة',
    'case.results.users': 'مستخدم',
    'case.results.for1video': 'لفيديو واحد',
    'packages.headline.growth': 'باقات',
    'packages.headline.packages': 'النمو.',
    'packages.popular': 'الأكثر شعبية',
    'packages.period': '/شهر',
    'packages.cta': 'قدم الآن',
    'packages.starter.name': 'مبتدئ',
    'packages.growth.name': 'نمو',
    'packages.authority.name': 'سلطة',
    'packages.feature.videos4': '4 مقاطع فيديو شهريًا',
    'packages.feature.videos6': '6 مقاطع فيديو شهريًا',
    'packages.feature.videos14': '14 مقطع فيديو شهريًا',
    'packages.feature.filming': 'تصوير احترافي',
    'packages.feature.editing': 'تحرير عالي الجودة',
    'packages.feature.concept': 'استراتيجية المفهوم',
    'packages.feature.distribution': 'تحسين التوزيع',
    'packages.feature.fullviral': 'استراتيجية انتشار كاملة',
    'packages.feature.priority': 'جدولة ذات أولوية',
    'packages.feature.manager': 'مدير حساب',
    'packages.budget.headline': 'هل لديك ميزانية مختلفة؟ لا مشكلة - سنقوم بتفصيل الباقة لتناسب احتياجاتك.',
    'packages.budget.cta': 'دعنا نتحدث.',
    'locations.headline.local': 'تركيز محلي.',
    'locations.headline.global': 'طموح عالمي.',
    'locations.hq': 'المقر الرئيسي',
    'locations.expanding': 'نتوسع قريباً',
    'contact.headline.lets': 'دعنا',
    'contact.headline.talk': 'نتحدث.',
    'contact.desc': 'هل أنت مستعد للسيطرة على سوقك المحلي؟ املأ النموذج وسنرد عليك في غضون 24 ساعة.',
    'contact.email': 'راسلنا',
    'contact.follow': 'تابعنا',
    'contact.form.name': 'الاسم',
    'contact.form.business': 'اسم الشركة',
    'contact.form.location': 'الموقع',
    'contact.form.revenue': 'الإيرادات الشهرية (اختياري)',
    'contact.form.revenue.select': 'اختر النطاق',
    'contact.form.goal': 'ما هو هدفك الرئيسي؟',
    'contact.form.cta': 'اطلب مكالمة استراتيجية',
    'authority.headline.numbers': 'الأرقام',
    'authority.headline.speak': 'تتحدث عن',
    'authority.headline.themselves': 'نفسها.',
    'authority.desc': "نحن لا نتحدث فقط عن الانتشار السريع. نحن نعيشه كل يوم. يتم اختبار استراتيجياتنا على الملايين قبل أن تصل إلى علامتك التجارية.",
    'authority.cta': 'تحقق على Instagram',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'customBudget.title': 'تسعير مرن لكل ميزانية',
    'customBudget.subtitle': 'هل لديك ميزانية أقل أو أعلى أو بين الأسعار المذكورة؟ لا مشكلة، يمكننا دائماً تعديل كمية الفيديو حسب احتياجاتك.',
    'customBudget.label': 'ميزانيتك المتاحة',
    'customBudget.cta': 'احصل على هذا العرض',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'AR' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
